#!/usr/bin/env python3
# 2026-08-13
# Fetch benchmark runs from SRA/ENA on demand, so that nothing here has to be mirrored on
# HuggingFace. `isalgo/umi_data` holds only the CI fixtures and the semi-internal data that has
# nowhere else to live; anything with a public accession is regenerated by this script instead.
#
#   probe   what the run IS -- reads per spot and their lengths, from metadata alone (no download).
#           This is the "does the UMI survive in the archive" test: a UMI on its own index read
#           shows up as nreads=3, and an inline one shows up as a mate longer than its partner.
#   url     the direct S3/HTTPS links, md5 and size (NCBI SDL + ENA portal).
#   peek    the first N spots as FASTQ, streamed. Enough for `migec suggest`.
#   get     the whole run: aria2c from S3, md5-checked, then fasterq-dump + gzip.
#
# ponytail: stdlib only (urllib/json/xml) plus whatever is on PATH. No pysradb, no requests --
# three GET requests and two subprocess calls do not need a dependency.

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
SDL = "https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve"
ENA = "https://www.ebi.ac.uk/ena/portal/api/search"
TIMEOUT = 60


def _get(url: str, params: dict) -> bytes:
    with urllib.request.urlopen(f"{url}?{urllib.parse.urlencode(params)}", timeout=TIMEOUT) as r:
        return r.read()


# --- probe ------------------------------------------------------------------------------------


def probe(accessions: list[str]) -> list[dict]:
    """Read structure and provenance for each run, from Entrez metadata only.

    The fields that decide whether a run is a migec input at all are `nreads` and the per-read
    lengths: a 3-read spot carries its UMI on a separate read, and two mates of different lengths
    usually mean one of them still has an inline barcode in front of the payload. Neither is proof
    -- `peek` into `migec suggest` is -- but it is free and it rules most runs out.
    """
    ids = json.loads(_get(f"{EUTILS}/esearch.fcgi", {
        "db": "sra", "term": " OR ".join(accessions), "retmax": len(accessions) * 4,
        "retmode": "json"}))["esearchresult"]["idlist"]
    if not ids:
        return []
    root = ET.fromstring(_get(f"{EUTILS}/efetch.fcgi", {
        "db": "sra", "id": ",".join(ids), "rettype": "xml"}).decode())

    wanted, rows = set(accessions), []
    for pkg in root.iter("EXPERIMENT_PACKAGE"):
        plat = next((e.tag for e in pkg.iter("PLATFORM") for e in e), "")
        model = next((e.text for e in pkg.iter("INSTRUMENT_MODEL")), "")
        # Scope this to the STUDY element: `pkg.iter("PRIMARY_ID")` unscoped finds the
        # EXPERIMENT's id first and silently reports SRX where SRP was meant.
        study = next((e.text for s in pkg.iter("STUDY") for e in s.iter("PRIMARY_ID")), "")
        bioproject = next((e.text for s in pkg.iter("STUDY") for e in s.iter("EXTERNAL_ID")
                           if e.get("namespace") == "BioProject"), "")
        strategy = next((e.text for e in pkg.iter("LIBRARY_STRATEGY")), "")
        layout = next((e.tag for e in pkg.iter("LIBRARY_LAYOUT") for e in e), "")
        for run in pkg.iter("RUN"):
            acc = run.get("accession")
            if acc not in wanted:
                continue
            stats = run.find("Statistics")
            lens = ([r.get("average") for r in stats.findall("Read")] if stats is not None else [])
            rows.append({
                "run": acc, "study": study, "bioproject": bioproject,
                "platform": plat, "model": model,
                "strategy": strategy, "layout": layout,
                "spots": run.get("total_spots", ""), "bases": run.get("total_bases", ""),
                "nreads": stats.get("nreads") if stats is not None else "",
                "read_lengths": ",".join(f"{float(x):g}" for x in lens if x),
            })
    return rows


def verdict(row: dict) -> str:
    """One line saying whether the archived run can still carry a UMI."""
    n = int(row["nreads"] or 0)
    lens = [float(x) for x in row["read_lengths"].split(",") if x]
    if n >= 3:
        return "3+ reads per spot: a separate index read, possibly the UMI -- peek to confirm"
    if n == 2 and len(lens) == 2 and abs(lens[0] - lens[1]) > 5:
        return "mates differ in length: one may still carry an inline barcode -- peek to confirm"
    if n == 2:
        return "two equal mates: no separate UMI read. Inline is still possible -- peek to confirm"
    return "single read: inline barcode or nothing -- peek to confirm"


# --- url / get --------------------------------------------------------------------------------


def locations(acc: str) -> list[dict]:
    """Direct links for the run: the NCBI .sra object first, then ENA's per-mate FASTQ.

    ENA is listed too because it serves the files as *submitted*, which for some studies means a
    third FASTQ that the SRA .sra object folded away.
    """
    out = []
    try:
        for res in json.loads(_get(SDL, {"acc": acc}))["result"]:
            for f in res.get("files", []):
                for loc in f.get("locations", []):
                    out.append({"source": f"ncbi-{loc['service']}", "url": loc["link"],
                                "size": f.get("size", ""), "md5": f.get("md5", ""),
                                # Never: SDL returns the ORIGINAL SUBMITTED files as well as the
                                # normalised .sra, and for some runs the submitted one comes
                                # first. Taking whichever is first and calling it `<acc>.sra`
                                # hands fasterq-dump a gzipped FASTQ. Keep the type and the real
                                # name and branch on them.
                                "type": f.get("type", ""), "name": f.get("name", "")})
    except Exception as exc:                      # noqa: BLE001 - one archive being down is not fatal
        print(f"  note: NCBI SDL unavailable for {acc}: {exc}", file=sys.stderr)
    try:
        tsv = _get(ENA, {"result": "read_run", "query": f"run_accession={acc}",
                         "fields": "fastq_ftp,fastq_md5,fastq_bytes", "format": "tsv"}).decode()
        rows = tsv.strip().split("\n")
        if len(rows) > 1:
            # ENA returns the columns in ITS canonical order, not the order asked for, so this
            # has to go through the header. Reading them positionally put the md5 in the url.
            rec = dict(zip(rows[0].split("\t"), rows[1].split("\t")))
            ftp = rec.get("fastq_ftp", "")
            md5s = rec.get("fastq_md5", "")
            sizes = rec.get("fastq_bytes", "")
            for u, m, s in zip(ftp.split(";"), md5s.split(";"), sizes.split(";")):
                if u:
                    out.append({"source": "ena-fastq", "url": f"https://{u}", "size": s, "md5": m})
    except Exception as exc:                      # noqa: BLE001
        print(f"  note: ENA unavailable for {acc}: {exc}", file=sys.stderr)
    return out


def _md5(path: Path) -> str:
    h = hashlib.md5()  # noqa: S324 - matching the archive's own checksum, not a security claim
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def download(url: str, dest: Path, expect_md5: str = "", conns: int = 8) -> Path:
    """aria2c if present, curl otherwise. Skips a file that is already there and checksums."""
    if dest.exists() and expect_md5 and _md5(dest) == expect_md5:
        print(f"  have {dest.name} (md5 ok)")
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    if shutil.which("aria2c"):
        cmd = ["aria2c", "-x", str(conns), "-s", str(conns), "-c", "--summary-interval=10",
               "-d", str(dest.parent), "-o", dest.name, url]
    elif shutil.which("curl"):
        cmd = ["curl", "-fL", "-C", "-", "-o", str(dest), url]
    else:
        raise SystemExit("need aria2c or curl on PATH")
    subprocess.run(cmd, check=True)
    if expect_md5:
        got = _md5(dest)
        if got != expect_md5:
            raise SystemExit(f"md5 mismatch for {dest}: {got} != {expect_md5}")
        print(f"  md5 ok {dest.name}")
    return dest


def get(acc: str, outdir: Path, conns: int, keep_sra: bool, prefer: str = "s3") -> None:
    """Fetch one run. NCBI S3 by default, ENA's FASTQ on request.

    Never: the obvious-looking choice is the slow one. ENA serves the FASTQ ready-made and skips
    the fasterq-dump step, so it looks like the lazy path -- but it caps at ONE connection.
    Measured on SRR17220895 from this machine: ENA 200 kB/s against NCBI S3 at **6.7 MB/s over 8
    connections**, a 33x difference, which is minutes against an hour over a study. The
    fasterq-dump step is worth paying. Use `--prefer ena` when the submitted files matter -- some
    studies deposit a third FASTQ that the .sra object folds away, and that is where a UMI on its
    own index read can still be hiding.
    """
    locs = locations(acc)
    ena = [x for x in locs if x["source"] == "ena-fastq"]
    if prefer == "ena" and ena:
        for x in ena:
            download(x["url"], outdir / Path(x["url"]).name, x["md5"], conns)
        return
    # Prefer the normalised `.sra`. SDL also lists the ORIGINAL SUBMITTED files, which for some
    # runs sort first -- SRR8255848's is `Platinum_Hifi2_S5_L001_R1_001.fastq.gz.1`, a gzipped
    # FASTQ. Downloading that under the name `<acc>.sra` and running fasterq-dump on it is how a
    # run silently produces nothing.
    ncbi = [x for x in locs if x["source"].startswith("ncbi-")]
    sra = next((x for x in ncbi if x.get("type") == "sra"), None)

    if sra is None:
        submitted = next((x for x in ncbi if x.get("name")), None)
        if submitted is not None:
            name = Path(submitted["name"]).name.removesuffix(".1")
            print(f"  note: no .sra for {acc}, taking the submitted {name}", file=sys.stderr)
            download(submitted["url"], outdir / name, submitted["md5"], conns)
            return
        if ena:
            for x in ena:
                download(x["url"], outdir / Path(x["url"]).name, x["md5"], conns)
            return
        raise SystemExit(f"no download location for {acc}")

    obj = download(sra["url"], outdir / f"{acc}.sra", sra["md5"], conns)
    if not shutil.which("fasterq-dump"):
        raise SystemExit(f"{obj} fetched; install sra-tools for fasterq-dump to convert it")
    subprocess.run(["fasterq-dump", "--split-files", "--include-technical",
                    "-O", str(outdir), str(obj)], check=True)
    for fq in sorted(outdir.glob(f"{acc}*.fastq")):
        subprocess.run(["gzip", "-1", "-f", str(fq)], check=True)
        print(f"  wrote {fq}.gz")
    if not keep_sra:
        obj.unlink()


# --- peek -------------------------------------------------------------------------------------


def peek(acc: str, n: int, outdir: Path) -> list[Path]:
    """First n spots as FASTQ, streamed from NCBI without fetching the run.

    Technical reads are kept: an index read holding the UMI is technical, and dropping it is
    exactly how a UMI goes missing between the archive and the analysis. sra-tools 3.x
    `fastq-dump` keeps them unless `--skip-technical` is passed -- it does NOT accept
    `--include-technical`, which is a `fasterq-dump` flag and errors out here.
    """
    if not shutil.which("fastq-dump"):
        raise SystemExit("need fastq-dump (sra-tools) on PATH for peek")
    outdir.mkdir(parents=True, exist_ok=True)
    subprocess.run(["fastq-dump", "-X", str(n), "--split-files", "-O", str(outdir), acc],
                   check=True)
    return sorted(outdir.glob(f"{acc}_*.fastq"))


# --- cli --------------------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("probe", help="read structure from metadata, no download")
    p.add_argument("accessions", nargs="+")
    p.add_argument("-o", "--out", type=Path, help="also write the table here as TSV")

    p = sub.add_parser("url", help="direct S3/HTTPS links, md5 and size")
    p.add_argument("accessions", nargs="+")

    p = sub.add_parser("peek", help="stream the first N spots as FASTQ")
    p.add_argument("accessions", nargs="+")
    p.add_argument("-n", "--spots", type=int, default=20000)
    p.add_argument("-o", "--out", type=Path, default=Path("peek"))

    p = sub.add_parser("get", help="fetch the whole run")
    p.add_argument("accessions", nargs="+")
    p.add_argument("-o", "--out", type=Path, default=Path("sra"))
    p.add_argument("-x", "--connections", type=int, default=8)
    p.add_argument("--keep-sra", action="store_true", help="do not delete the .sra after conversion")
    p.add_argument("--prefer", choices=["s3", "ena"], default="s3",
                   help="s3 (default, ~33x faster here) or ena (the submitted FASTQ files)")

    a = ap.parse_args()

    if a.cmd == "probe":
        rows = probe(a.accessions)
        cols = ["run", "study", "bioproject", "model", "strategy", "layout", "spots", "nreads",
                "read_lengths"]
        print("\t".join(cols))
        for r in sorted(rows, key=lambda r: a.accessions.index(r["run"])):
            print("\t".join(str(r[c]) for c in cols))
        print(file=sys.stderr)
        for r in rows:
            print(f"{r['run']}: {verdict(r)}", file=sys.stderr)
        missing = set(a.accessions) - {r["run"] for r in rows}
        for m in sorted(missing):
            print(f"{m}: not found in SRA", file=sys.stderr)
        if a.out:
            a.out.write_text("\t".join(cols) + "\n"
                             + "".join("\t".join(str(r[c]) for c in cols) + "\n" for r in rows))

    elif a.cmd == "url":
        for acc in a.accessions:
            print(f"# {acc}")
            for loc in locations(acc):
                print(f"{loc['source']}\t{loc.get('type', '')}\t{loc['size']}\t{loc['md5']}\t"
                      f"{loc['url']}")

    elif a.cmd == "peek":
        for acc in a.accessions:
            for f in peek(acc, a.spots, a.out):
                print(f)

    elif a.cmd == "get":
        for acc in a.accessions:
            print(f"# {acc}")
            get(acc, a.out, a.connections, a.keep_sra, a.prefer)


if __name__ == "__main__":
    main()
